/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JInternalFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Calculator");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setBackground(new java.awt.Color(51, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("0");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setOpaque(true);

        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        jButton27.setBackground(new java.awt.Color(25, 42, 86));
        jButton27.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("AC");
        jButton27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton27.setContentAreaFilled(false);
        jButton27.setOpaque(true);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton27);

        jButton34.setBackground(new java.awt.Color(25, 42, 86));
        jButton34.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton34.setForeground(new java.awt.Color(255, 255, 255));
        jButton34.setText("C");
        jButton34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton34.setContentAreaFilled(false);
        jButton34.setOpaque(true);
        jPanel2.add(jButton34);

        jButton32.setBackground(new java.awt.Color(25, 42, 86));
        jButton32.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton32.setForeground(new java.awt.Color(255, 255, 255));
        jButton32.setText("%");
        jButton32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton32.setContentAreaFilled(false);
        jButton32.setOpaque(true);
        jPanel2.add(jButton32);

        jButton31.setBackground(new java.awt.Color(25, 42, 86));
        jButton31.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("/");
        jButton31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton31.setContentAreaFilled(false);
        jButton31.setOpaque(true);
        jPanel2.add(jButton31);

        jButton33.setBackground(new java.awt.Color(72, 126, 176));
        jButton33.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton33.setText("7");
        jButton33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton33.setContentAreaFilled(false);
        jButton33.setOpaque(true);
        jPanel2.add(jButton33);

        jButton23.setBackground(new java.awt.Color(72, 126, 176));
        jButton23.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton23.setText("8");
        jButton23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton23.setContentAreaFilled(false);
        jButton23.setOpaque(true);
        jPanel2.add(jButton23);

        jButton26.setBackground(new java.awt.Color(72, 126, 176));
        jButton26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton26.setText("9");
        jButton26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton26.setContentAreaFilled(false);
        jButton26.setOpaque(true);
        jPanel2.add(jButton26);

        jButton24.setBackground(new java.awt.Color(25, 42, 86));
        jButton24.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("*");
        jButton24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton24.setContentAreaFilled(false);
        jButton24.setOpaque(true);
        jPanel2.add(jButton24);

        jButton20.setBackground(new java.awt.Color(72, 126, 176));
        jButton20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton20.setText("4");
        jButton20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton20.setContentAreaFilled(false);
        jButton20.setOpaque(true);
        jPanel2.add(jButton20);

        jButton28.setBackground(new java.awt.Color(72, 126, 176));
        jButton28.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton28.setText("5");
        jButton28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton28.setContentAreaFilled(false);
        jButton28.setOpaque(true);
        jPanel2.add(jButton28);

        jButton30.setBackground(new java.awt.Color(72, 126, 176));
        jButton30.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton30.setText("6");
        jButton30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton30.setContentAreaFilled(false);
        jButton30.setOpaque(true);
        jPanel2.add(jButton30);

        jButton29.setBackground(new java.awt.Color(25, 42, 86));
        jButton29.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("-");
        jButton29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton29.setContentAreaFilled(false);
        jButton29.setOpaque(true);
        jPanel2.add(jButton29);

        jButton35.setBackground(new java.awt.Color(72, 126, 176));
        jButton35.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton35.setText("1");
        jButton35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton35.setContentAreaFilled(false);
        jButton35.setOpaque(true);
        jPanel2.add(jButton35);

        jButton21.setBackground(new java.awt.Color(72, 126, 176));
        jButton21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton21.setText("2");
        jButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton21.setContentAreaFilled(false);
        jButton21.setOpaque(true);
        jPanel2.add(jButton21);

        jButton22.setBackground(new java.awt.Color(72, 126, 176));
        jButton22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton22.setText("3");
        jButton22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton22.setContentAreaFilled(false);
        jButton22.setOpaque(true);
        jPanel2.add(jButton22);

        jButton25.setBackground(new java.awt.Color(25, 42, 86));
        jButton25.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("+");
        jButton25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton25.setContentAreaFilled(false);
        jButton25.setOpaque(true);
        jPanel2.add(jButton25);

        jButton39.setBackground(new java.awt.Color(72, 126, 176));
        jButton39.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton39.setText("+/-");
        jButton39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton39.setContentAreaFilled(false);
        jButton39.setOpaque(true);
        jPanel2.add(jButton39);

        jButton38.setBackground(new java.awt.Color(72, 126, 176));
        jButton38.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton38.setText("0");
        jButton38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton38.setContentAreaFilled(false);
        jButton38.setOpaque(true);
        jPanel2.add(jButton38);

        jButton37.setBackground(new java.awt.Color(72, 126, 176));
        jButton37.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton37.setText(".");
        jButton37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton37.setContentAreaFilled(false);
        jButton37.setOpaque(true);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton37);

        jButton36.setBackground(new java.awt.Color(255, 153, 0));
        jButton36.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 255, 255));
        jButton36.setText("=");
        jButton36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton36.setContentAreaFilled(false);
        jButton36.setOpaque(true);
        jPanel2.add(jButton36);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
